### PR TITLE
U iinterface

### PR DESCRIPTION
**Pull request by QUIN04**
## Description

Please describe your changes and the problem you are solving.

## Changes Made

- List the changes you made here
- Be specific and clear
- Include any relevant details

## Checklist

- [ ] Tests have been added or updated
- [ ] Documentation has been updated
- [x] The code follows the project's style guide
- [x] Any relevant configuration files have been updated

## Screenshots (if applicable)

Please attach any relevant screenshots that show the changes made.

### CODE REVIEW

**Review by TabotCharlesBessong — CHANGES_REQUESTED** [review]
- Always test your code locally before making a pull request
- Try as much as possible to have screenshots especially when you are working in the frontend, this will show what you did
- Check index.html file, in there it is looking for main.jsx, so it had to be changed to main.tsx

**Comment by TabotCharlesBessong** [comment]
- When you make a pull request, check if you have conflicts
- Resolve them when you do
- Always make sure the branch ahead of the branch you are working on is up to date to avoid conflicts

**Review by TabotCharlesBessong — COMMENTED** [review]
- What was yesterdays mistake. 
- Please let the commit message describe what you did in a way others can understand you

**Comment by QUIN04** [comment]
> * When you make a pull request, check if you have conflicts
> * Resolve them when you do
> * Always make sure the branch ahead of the branch you are working on is up to date to avoid conflicts

Thanks for the remarks and feedbacks, I'll improve on all of them

**Pull request closed without merging**
